const Contacts = [
  {
    pid: "XRTQPLWMEY",
    name: "Alice Johnson",
    pfp: "https://i.pinimg.com/736x/c0/1b/10/c01b109bcb43eaffa1c2adb1ba0bebc5.jpg",
    email: "alice.johnson@example.com",
  },
  {
    pid: "ASDUIWQMNB",
    name: "Bob Smith",
    pfp: "https://i.pinimg.com/236x/a5/67/94/a567940c61eb580455d8f886f55d21b1.jpg",
    email: "bob.smith@example.com",
  },
  {
    pid: "PLKJQOIWUY",
    name: "Charlie Davis",
    pfp: "https://i.pinimg.com/1200x/29/e1/a0/29e1a00e7f20462520efd29fe8f2a4f9.jpg",
    email: "charlie.davis@example.com",
  },
  {
    pid: "MQIWUTRNBG",
    name: "Diana Evans",
    pfp: "https://i.pinimg.com/736x/72/e3/35/72e33544be42e1949ca43b6c44689123.jpg",
    email: "diana.evans@example.com",
  },
  {
    pid: "WQPIOERBNX",
    name: "Ethan Parker",
    pfp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHwxJ6zp7kThWufF_nfOyK3az0Ek_Of_CPmt_hjHimA__z7_UABgGvXpBsXaVZ7_ANkhs&usqp=CAU",
    email: "ethan.parker@example.com",
  },
  {
    pid: "LPQWOERUIX",
    name: "Fiona Brown",
    pfp: "https://i.pinimg.com/736x/39/34/1a/39341ac32898c0a5d0d3fc189cda0f79.jpg",
    email: "fiona.brown@example.com",
  },
  {
    pid: "QWERTYUJKL",
    name: "George Wilson",
    pfp: "",
    email: "george.wilson@example.com",
  },
  {
    pid: "IOPASDFGHJ",
    name: "Hannah Taylor",
    pfp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsBaZBFYOauOSkjTqK2MEoFUZpEPoljrypgQ&s",
    email: "hannah.taylor@example.com",
  },
  {
    pid: "MNBVCXZLKJ",
    name: "Isaac Lewis",
    pfp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMq9c1maFFgxxwuvp371vHyXL1C-Xtbu0H2A&s",
    email: "isaac.lewis@example.com",
  },
  {
    pid: "LKJHGFDSAQ",
    name: "Julia Clark",
    pfp: "https://i.pinimg.com/736x/12/3d/5e/123d5e17e0efbd9c3818f576cf9d5f3a.jpg",
    email: "julia.clark@example.com",
  },
  {
    pid: "POIUYTREWQ",
    name: "Kevin Adams",
    pfp: "https://img.freepik.com/premium-photo/smiling-adult-man_1030879-121332.jpg?semt=ais_hybrid",
    email: "kevin.adams@example.com",
  },
  {
    pid: "QAZWSXEDCR",
    name: "Lily Martinez",
    pfp: "",
    email: "lily.martinez@example.com",
  },
  {
    pid: "ZXCVMNBPOI",
    name: "Martin Hall",
    pfp: "",
    email: "martin.hall@example.com",
  },
  {
    pid: "UIOPMNBVXZ",
    name: "Olivia Brooks",
    pfp: "",
    email: "olivia.brooks@example.com",
  },
  {
    pid: "YXWVUTSRQP",
    name: "Patrick Lee",
    pfp: "",
    email: "patrick.lee@example.com",
  },
  {
    pid: "PLMNOKIJHG",
    name: "Quincy Foster",
    pfp: "",
    email: "quincy.foster@example.com",
  },
  {
    pid: "MBVXZNLAKS",
    name: "Rachel Moore",
    pfp: "",
    email: "rachel.moore@example.com",
  },
  {
    pid: "LOPKMJNHGB",
    name: "Samuel Wright",
    pfp: "",
    email: "samuel.wright@example.com",
  },
  {
    pid: "NBMVCXZQPO",
    name: "Tina King",
    pfp: "",
    email: "tina.king@example.com",
  },
  {
    pid: "YTREWSDFVB",
    name: "Uma Patel",
    pfp: "",
    email: "uma.patel@example.com",
  },
  {
    pid: "KLOPQWERTY",
    name: "Victor Green",
    pfp: "",
    email: "victor.green@example.com",
  },
  {
    pid: "ZXCVBNMPLA",
    name: "Wendy Hughes",
    pfp: "https://images.generated.photos/9Mq34ypVJd71kEEJplvCHR2dPzsNQ60Q5Fux-_cvXcE/rs:fit:256:256/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MDAyNjMzLmpwZw.jpg",
    email: "wendy.hughes@example.com",
  },
  {
    pid: "NMLOPKJUHY",
    name: "Xander Scott",
    pfp: "",
    email: "xander.scott@example.com",
  },
  {
    pid: "PAOSIDFNMB",
    name: "Yara Cruz",
    pfp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa9aviu7HRiUrDyoQ52atSrL4o7bljG2OxoVNIZWN4iizWFR2N94D3A9I1l_pCWN7r3JE&usqp=CAU",
    email: "yara.cruz@example.com",
  },
  {
    pid: "WERASDZXCQ",
    name: "Zoe Walker",
    pfp: "",
    email: "zoe.walker@example.com",
  },
  {
    pid: "QWERTASDGH",
    name: "Ben Anderson",
    pfp: "",
    email: "ben.anderson@example.com",
  },
  {
    pid: "ZXCVQWEASD",
    name: "Clara Bell",
    pfp: "",
    email: "clara.bell@example.com",
  },
  {
    pid: "MLPOIUYTRE",
    name: "Derek White",
    pfp: "",
    email: "derek.white@example.com",
  },
  {
    pid: "VCXZQPLKJH",
    name: "Eva Diaz",
    pfp: "",
    email: "eva.diaz@example.com",
  },
  {
    pid: "IUYTMLPOQW",
    name: "Frank Collins",
    pfp: "",
    email: "frank.collins@example.com",
  },
];

export default Contacts;
